### ISSUE TITLE
Add support to authenticate with Storage without using `DefaultAzureCredential`

### ISSUE THREAD

**Issue by liammoat** [microsoft/FHIR-Converter#559]
We are currently testing the `fhir-converter` service. We are running it locally in our development environment using Docker Compose. We would like to use [azurite](https://github.com/Azure/Azurite) to emulate Azure Storage. This enables us to run offline and means we can run our template test suite locally, and in CI/CD, without deploying Azure infrastructure.

Here is a snippet from our `docker-compose.yml`:

```yaml
  azure-storage-emulator:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./mounted-data/azure-storage:/data
      - ./mounted-data/certs:/certs
    command:
      - "azurite"
      - "--oauth"
      - "basic"
      - "--blobHost"
      - "0.0.0.0"
      - "--tableHost"
      - "0.0.0.0"
      - "--cert"
      - "/certs/127.0.0.1.pem"
      - "--key"
      - "/certs/127.0.0.1-key.pem"

  fhir-converter:
    image: "mcr.microsoft.com/healthcareapis/fhir-converter:1.0.0-preview"
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      TemplateHosting__StorageAccountConfiguration__ContainerUrl: "https://azure-storage-emulator:10000/devstoreaccount1/templates"
    depends_on:
      azure-storage-emulator:
        condition: service_started
```

At present, `fhir-converter` hardcodes the use of `DefaultAzureCredential` to authenticate with Storage (see [here](https://github.com/microsoft/FHIR-Converter/blob/575fd14eb890e9d2946a323a9e29bd6be43ec937/src/Microsoft.Health.Fhir.TemplateManagement/Factory/ConvertDataTemplateCollectionProviderFactory.cs#L76)). While a good practice for local development and in Azure, it introduces complexity in some environments (docker compose being one of them).

1. The use of `TokenCredential` with the storage client mandates a `https` endpoint. This requires additional configuration and complexity when using `azurite` to configure certificates etc. 

    ```
    Unhandled exception. System.ArgumentException: Cannot use TokenCredential without HTTPS.
        at Azure.Storage.Errors.VerifyHttpsTokenAuth(Uri uri)
    ```

2. The use of `DefaultAzureCredential` also requires a valid Azure credential to be available in the local container. Error is: "Failed to connect to blob template store - DefaultAzureCredential failed to retrieve a token from the included credentials."

    ![image](https://github.com/microsoft/FHIR-Converter/assets/2767292/d32b74f4-73d9-4b6d-9e76-d4c1536f679d)

Both challenges could be resolved by allowing the option to provide a storage connection string - which can be optionally used when instantiating `BlobContainerClient`.
